---
deployment:
  tasks:
    - echo "🚀 Начинаем развертывание Django-приложения..."

    - echo "📂 Переходим в папку проекта..."
    - cd ~/public_html/your_project_folder  # Убедитесь, что путь правильный

    - echo "🐍 Активируем виртуальное окружение..."
    - source ~/venv/bin/activate  # Путь к виртуальному окружению

    - echo "📦 Устанавливаем зависимости..."
    - pip install -r requirements.txt

    - echo "🔄 Применяем миграции..."
    - python manage.py migrate

    - echo "🎨 Собираем статические файлы..."
    - python manage.py collectstatic --noinput

    - echo "🔁 Перезапускаем сервер..."
    - touch ~/tmp/restart.txt  # Это обновит сервер

    - echo "✅ Развертывание завершено!"
