# Generated by Django 5.0 on 2024-04-17 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
    name='MyObject',
    fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('address', models.CharField(default='Vilnius', max_length=255)),
        ('start_date', models.DateField(default=django.utils.timezone.now)),
        ('end_date', models.DateField(default=django.utils.timezone.now)),
        ('customer_name', models.CharField(default='Name', max_length=255)),
        ('executor_name', models.CharField(default='Valery', max_length=255)),
        ('documents', models.FileField(default='documents/Договор_Visatos_Platuma_Valery.pdf', upload_to='documents/')),
        ('name', models.CharField(blank=True, max_length=255, null=True)),  # Добавьте это определение поля
    ],
),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dat_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyCurrentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_object_name', models.CharField(default='none', max_length=100)),
                ('my_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.myobject')),
            ],
        ),
    ]
