# Generated by Django 5.0 on 2024-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_myobject_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobject',
            name='documents',
            field=models.FileField(default='documents/Договор_Visatos_Platuma_Valery.pdf', upload_to='documents/'),
        ),
    ]
