# Generated by Django 5.0 on 2024-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_myobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCurrentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
            ],
        ),
    ]
