# Generated by Django 5.0 on 2024-04-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_mycurrentobject_my_object_name_workdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='my_current_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='catalog.mycurrentobject'),
        ),
    ]
