# Generated by Django 5.0 on 2024-05-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_myobject_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetail',
            name='my_current_object',
        ),
        migrations.AddField(
            model_name='workdetail',
            name='my_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='catalog.myobject'),
            preserve_default=False,
        ),
    ]
