# Generated by Django 5.0 on 2024-04-18 09:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_workdetail_my_current_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycurrentobject',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
