# Generated by Django 5.0 on 2024-05-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_workdetail_my_current_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetail',
            name='my_object',
        ),
        migrations.AddField(
            model_name='workdetail',
            name='my_current_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='catalog.mycurrentobject'),
            preserve_default=False,
        ),
    ]
