# Generated by Django 5.0 on 2024-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_mycurrentobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycurrentobject',
            name='end_date',
        ),
        migrations.AddField(
            model_name='mycurrentobject',
            name='MyObject',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
