# Generated by Django 5.0 on 2024-04-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_mycurrentobject_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycurrentobject',
            old_name='MyObject',
            new_name='my_object_name',
        ),
        migrations.RemoveField(
            model_name='myobject',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myobject',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='myobject',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='myobject',
            name='executor_name',
        ),
        migrations.RemoveField(
            model_name='myobject',
            name='start_date',
        ),
        migrations.AddField(
            model_name='mycurrentobject',
            name='my_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.myobject'),
        ),
    ]
