# Generated by Django 5.0 on 2024-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_mycurrentobject_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
