# Generated by Django 5.0 on 2024-05-21 06:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_myobject_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='myobject',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.generate_filename),
        ),
    ]
