# Generated by Django 5.0 on 2024-04-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_note_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
    ]
