# Generated by Django 5.0 on 2024-04-16 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_myobject_address_myobject_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobject',
            name='documents',
            field=models.FileField(default='documents/Договор_Visatos_Platuma_Valery.pdf', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myobject',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myobject',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
