# Generated by Django 5.0 on 2024-07-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
