# Generated by Django 5.0 on 2024-04-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
    ]
