# Generated by Django 5.0 on 2024-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
