# Generated by Django 5.0 on 2024-04-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_workdetail_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycurrentobject',
            name='total_object_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
