# Generated by Django 5.0 on 2024-04-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_mycurrentobject_total_object_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycurrentobject',
            name='total_object_price',
        ),
    ]
