# Generated by Django 5.0 on 2024-04-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
